"""alter_table_area_doc_no_non_unique

Revision ID: 469aafe4d8d7
Revises: e16bad1f8fd5
Create Date: 2026-05-22 20:37:51.048805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469aafe4d8d7'
down_revision: Union[str, Sequence[str], None] = 'e16bad1f8fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('areas_doc_no_key'), 'areas', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('areas_doc_no_key'), 'areas', ['doc_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
