"""create_table_mto_all

Revision ID: 78eda70b63aa
Revises: 469aafe4d8d7
Create Date: 2026-05-25 12:01:34.084092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78eda70b63aa'
down_revision: Union[str, Sequence[str], None] = '469aafe4d8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(), nullable=False),
    sa.Column('reference_mto', sa.String(), nullable=False),
    sa.Column('mto_date', sa.DateTime(), nullable=False),
    sa.Column('pid_no', sa.String(), nullable=True),
    sa.Column('line_no', sa.String(), nullable=True),
    sa.Column('isometric_drawing_no', sa.String(), nullable=True),
    sa.Column('iso_rev', sa.String(), nullable=True),
    sa.Column('iso_and_rev', sa.String(), nullable=True),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('required_area', sa.Float(), nullable=True),
    sa.Column('required_iso', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('area_2_id', sa.Integer(), nullable=True),
    sa.Column('area_2_desc_id', sa.Integer(), nullable=True),
    sa.Column('stock_data_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_2_desc_id'], ['descriptions.id'], ),
    sa.ForeignKeyConstraint(['area_2_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['stock_data_id'], ['stock_data.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mto_date', 'mtos', ['mto_date'], unique=False)
    op.create_index('idx_mto_reference', 'mtos', ['reference_mto', 'no', 'line_no'], unique=False)
    op.create_index('idx_mto_stock_data', 'mtos', ['stock_data_id'], unique=False)
    op.create_index(op.f('ix_mtos_area_2_desc_id'), 'mtos', ['area_2_desc_id'], unique=False)
    op.create_index(op.f('ix_mtos_area_2_id'), 'mtos', ['area_2_id'], unique=False)
    op.create_index(op.f('ix_mtos_area_id'), 'mtos', ['area_id'], unique=False)
    op.create_index(op.f('ix_mtos_created_by_id'), 'mtos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_mtos_location_id'), 'mtos', ['location_id'], unique=False)
    op.create_index(op.f('ix_mtos_stock_data_id'), 'mtos', ['stock_data_id'], unique=False)
    op.create_index(op.f('ix_mtos_uom_id'), 'mtos', ['uom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtos_uom_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_stock_data_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_location_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_created_by_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_area_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_area_2_id'), table_name='mtos')
    op.drop_index(op.f('ix_mtos_area_2_desc_id'), table_name='mtos')
    op.drop_index('idx_mto_stock_data', table_name='mtos')
    op.drop_index('idx_mto_reference', table_name='mtos')
    op.drop_index('idx_mto_date', table_name='mtos')
    op.drop_table('mtos')
    # ### end Alembic commands ###
